
services:
  fastapi:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "49152:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
