
name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'release/**'  # optional: trigger on release branches too
  pull_request:
    branches:
      - main
      - 'release/**'  # optional: trigger on PRs targeting these

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          DATABASE_URL: "sqlite:///./default.db"  # dummy value
        run: |
          pytest
